<?php

namespace Tests\Feature;

use App\Entities\Transferencia;
use App\Entitys\Nfse\Servico;
use App\Enum\EnumMensagensDeErro;
use App\Exceptions\TransferenciaException;
use App\Helpers\HelpersFile;
use App\Http\Services\ServicesTransferencia;

use App\Models\Saldo;
use App\Models\Transferencia_item;
use App\Providers\ServicesTransferenciasProvider;
use Illuminate\Foundation\Application;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Http\Response;
use Tests\TestCase;

class TransferenciasTest extends TestCase
{
    use DatabaseTransactions;

    protected Transferencia | null $Transferencia;
    protected array | null $jsonBase;

    protected ServicesTransferencia | null $ServicesTransferencia;

    protected  $jsonRabbit;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->Transferencia = new Transferencia();

        $this->jsonBase = json_decode(HelpersFile::getConteudoArquivo("tests/Json/JsonTransferenciaBase.json"), true);

        $this->ServicesTransferencia = app(ServicesTransferencia::class);

        $this->jsonRabbit = json_decode(HelpersFile::getConteudoArquivo("tests/Json/JsonRabbit.json"));

    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        $this->Transferencia = null;

        $this->jsonBase = null;

        $this->ServicesTransferencia = null;

        $this->jsonRabbit = null;
    }

    public function testCriarObjetoTransferencia()
    {
        $this->Transferencia->elaborarObjeto($this->jsonBase["transferencias"][0]);

        $this->assertFalse($this->Transferencia->infoError());
        $this->assertEmpty($this->Transferencia->infoMessageErro());

        $this->assertNotNull($this->Transferencia->infoValor());

        $this->assertGreaterThan(0, $this->Transferencia->infoValor());
    }

    public function testObjetoTransferenciaComValorZerado()
    {
        $this->jsonBase["transferencias"][0]["valor"] = 0;

        $this->Transferencia->elaborarObjeto($this->jsonBase["transferencias"][0]);

        $this->assertTrue($this->Transferencia->infoError());
        $this->assertNotEmpty($this->Transferencia->infoMessageErro());
    }

    public function testCriarJsonResponse()
    {
        $this->Transferencia->elaborarObjeto($this->jsonBase["transferencias"][0]);

        $resultJson = $this->Transferencia->jsonSerialize();

        $this->assertJson($resultJson);

        $this->assertNotEmpty($resultJson);
        $this->assertNotNull($resultJson);
    }

    public function testCriarListaDeTransferencias()
    {
        $result = $this->ServicesTransferencia->criarListaDeTransferencia($this->jsonBase);

        $this->assertIsArray($result);

        $this->assertArrayHasKey("transferencias", $result);
        $this->assertGreaterThan(0, count($result["transferencias"]));

        $this->assertArrayHasKey("valorTotal", $result);
        $this->assertIsNumeric($result["valorTotal"]);
        $this->assertNotNull($result["valorTotal"]);
        $this->assertNotEmpty($result["valorTotal"]);

    }

    public function testInformarExceptionAoCriarListaDeTransferencias()
    {
        $this->jsonBase["transferencias"][0]["valor"] = 0;

        $this->expectException(TransferenciaException::class);
        $this->expectExceptionCode(Response::HTTP_BAD_REQUEST);

        $this->ServicesTransferencia->criarListaDeTransferencia($this->jsonBase);
    }

    public function testValidarSaldoDisponivel()
    {
        auth()->loginUsingId(10);

        $result = $this->ServicesTransferencia->validarSaldoDisponivel(1337);

        $this->assertIsBool($result);
        $this->assertTrue($result);

        $this->assertNotEmpty($result);
        $this->assertNotNull($result);
    }
    public function testReceberExceptionAoValidarSaldoDisponivel()
    {
        auth()->loginUsingId(10);

        $this->expectException(TransferenciaException::class);
        $this->expectExceptionCode(Response::HTTP_CONFLICT);
        $this->expectExceptionMessage(EnumMensagensDeErro::SALDO_INSUFICIENTE->value);

        $this->ServicesTransferencia->validarSaldoDisponivel(999999.99);
    }

    public function testSalvarTransferencia()
    {
        auth()->loginUsingId(10);

        $result = $this->ServicesTransferencia->criarListaDeTransferencia($this->jsonBase);

        $Transferencia = $this->ServicesTransferencia->salvarTransferencia($result);

        $this->assertInstanceOf(\App\Models\Transferencia::class, $Transferencia);

        $this->assertNotNull($Transferencia->id);
        $this->assertNotNull($Transferencia->vl_total);
        $this->assertNotNull($Transferencia->pessoa_origem);

        $this->assertIsInt($Transferencia->pessoa_origem);
        $this->assertIsInt($Transferencia->id);
    }

    public function SalvarItensTransferencia() #apensa para debug
    {
        auth()->loginUsingId(10);

        $result = $this->ServicesTransferencia->criarListaDeTransferencia($this->jsonBase);

        $Transferencia = $this->ServicesTransferencia->salvarTransferencia($result);

        $this->ServicesTransferencia->salvarItensTransferencia($Transferencia, $result["transferencias"]);


    }

    public function testSalvarNovoSaldo()
    {
        auth()->loginUsingId(10);

        $saldoAtual = Saldo::where("bo_ativo", 1)->where("pessoa_id", auth()->user()->pessoa_id)->first()->vl_saldo;

        $result = $this->ServicesTransferencia->criarListaDeTransferencia($this->jsonBase);

        $Transferencia = $this->ServicesTransferencia->salvarTransferencia($result);

        $this->ServicesTransferencia->salvarNovoSaldo($Transferencia, $result["valorTotal"]);

        $novoSaldo = Saldo::where("bo_ativo", 1)->where("pessoa_id", auth()->user()->pessoa_id)->first()->vl_saldo;

        $this->assertNotEquals($saldoAtual, $novoSaldo);
        $this->assertGreaterThan($novoSaldo, $saldoAtual);
    }

    public function ExtornarValores() #apenas para debug
    {
        $saldoAntigo = Saldo::where("bo_ativo", 1)->where("pessoa_id", 26)->first()->vl_saldo;

        $this->ServicesTransferencia->reembolsarTransferencia($this->jsonRabbit);

        $novoSaldo = Saldo::where("bo_ativo", 1)->where("pessoa_id", 1)->first()->vl_saldo;

        $this->assertGreaterThan($saldoAntigo, $novoSaldo);
    }

}
